collections:
  authors:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor
  - node_modules


title: GitHub Workshop
email: education@github.com
description: > # Find your local campus expert and keep up with their activities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://viit-vignite.ml/workshop" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  saibhaskar24


defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag